---
output:
  md_document:
    variant: markdown_github
    pandoc_args: [
      "--atx-headers"
    ]
---

# 第6章 2変数の関連を調べよう！

## 1. 単相関係数

化粧品代と洋服代のアンケート結果

```{r}
makeup <- c(3000, 5000, 12000, 2000, 7000, 15000, 5000, 6000, 8000, 10000)
clothes <- c(7000, 8000, 25000, 5000, 12000, 30000, 10000, 15000, 20000, 18000)
```

グラフ

```{r}
plot(makeup, clothes)
```

単相関係数

```{r}
cor(makeup, clothes)
```

## 2. 相関比

年齢と好きな洋服のブランド

```{r}
survey.age <- c(27, 33, 16, 29, 32, 23, 25, 28, 22, 18, 26, 26, 15, 29, 26)
survey.brand <- c("Theremes", "Channelior", "Bureperry", "Bureperry", "Channelior", "Theremes",
                  "Channelior", "Theremes", "Bureperry", "Bureperry", "Channelior", "Theremes",
                  "Bureperry", "Channelior", "Bureperry")
```

集計

```{r}
tapply(survey.age, survey.brand, identity)
```

グラフ

```{r}
stripchart(tapply(survey.age, survey.brand, identity), vertical = TRUE)
```

相関比を求める関数

```{r}
correlation.ratio <- function(value, category) summary(lm(value ~ category))$r.squared
```

相関比

```{r}
correlation.ratio(survey.age, survey.brand)
```

## 3. クラメールの連関係数

クロス集計表

```{r}
asked.out.table <- matrix(c(34, 61, 53, 38, 40, 74), byrow = TRUE, nrow = 2)
```

```{r}
asked.out.table
```

今回は[vcdパッケージ](https://cran.r-project.org/web/packages/vcd/index.html)を使ってクラメールの連関係数を計算する。

パッケージのインストール

```{r message = FALSE, results = "hide"}
install.packages("vcd")
```

パッケージの読み込み

```{r message = FALSE}
library(vcd)
```

計算

```{r}
assocstats(asked.out.table)
```

クラメールの連関係数のみを取り出す

```{r}
assocstats(asked.out.table)$cramer
```
